Repository SDSamarasinghe/Top_Jobs_Crooby_Beans, pull requests merged in 2022-05, with the labels that each got.

#5 create java files validations and edit ui designs
  .idea/misc.xml
  app/src/main/res/layout/activity_edit_jobreq.xml
  app/src/main/res/layout/activity_homepage_new.xml
  app/src/main/res/layout/activity_my_requested_jobs.xml
  app/src/main/res/layout/activity_new_save_req_jobs.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/activity_view_req_job.xml
  app/src/main/res/layout/activity_viewjob_m.xml
  app/src/main/res/layout/homepage_item.xml
  app/src/main/res/layout/listing_card.xml
  app/src/main/res/layout/reqjob_item.xml
  app/src/main/res/layout/save_reqjob_item.xml
  app/src/main/res/layout/savejobs_item.xml
  app/src/main/res/layout/toolbar1.xml
Labels: bug, enhancement

#7 create navbar
  .idea/misc.xml
  app/src/main/res/drawable/calaculator.jpg
  app/src/main/res/drawable/newlogomad.jpeg
  app/src/main/res/drawable/peaple.jpg
  app/src/main/res/drawable/profilenew.png
  app/src/main/res/drawable/requestedjob.png
  app/src/main/res/drawable/suitacse.png
  app/src/main/res/layout/activity_navigation_bar.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#8 user_registration,user_login,edit delete jobs,create some changes
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mysaved/EditJob.java
  app/src/main/java/com/example/mysaved/RegisterUserActivity.java
  app/src/main/java/com/example/mysaved/UserloginActivity.java
  app/src/main/java/com/example/mysaved/my_salary_calc.java
  app/src/main/res/drawable/border_reg.xml
  app/src/main/res/drawable/log_panel.xml
  app/src/main/res/drawable/logo.jpeg
  app/src/main/res/drawable/logo.png
  app/src/main/res/layout/activity_edit_job.xml
  app/src/main/res/layout/activity_my_salary_calc.xml
  app/src/main/res/layout/activity_userlogin.xml
  app/src/main/res/layout/register_user.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#6 Create send Request job page and view data to firebase.
  app/src/main/res/drawable/jslogo.png
  app/src/main/res/layout/activity_requestjob.xml
  app/src/main/res/values/strings.xml
Labels: bug

#9 Navigation
  .idea/misc.xml
  app/src/main/res/layout/activity_my_job_listings.xml
  app/src/main/res/layout/activity_new_req_job_homepage.xml
Labels: duplicate, enhancement

#10 Feature/usermanage2
  .idea/misc.xml
  app/src/main/java/com/example/mysaved/UserloginActivity.java
  app/src/main/res/layout/activity_userlogin.xml
  app/src/main/res/layout/register_user.xml
Labels: bug, documentation, duplicate, enhancement

#11 updated navigation bar UI
  app/src/main/java/com/example/mysaved/RequestJob.java
  app/src/main/res/layout/activity_navigation_bar.xml
Labels: duplicate

#12 Feature/career2
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_my_requested_jobs.xml
  app/src/main/res/layout/activity_view_job.xml
  app/src/main/res/layout/toolbar1.xml
Labels: enhancement

#13 Create Icon logo with foreground and background.
  .idea/misc.xml
  app/src/main/res/mipmap-hdpi/logo_foreground.png
  app/src/main/res/mipmap-hdpi/logo_launcher.png
  app/src/main/res/mipmap-mdpi/logo_foreground.png
  app/src/main/res/mipmap-mdpi/logo_launcher.png
  app/src/main/res/mipmap-xhdpi/logo_foreground.png
  app/src/main/res/mipmap-xhdpi/logo_launcher.png
  app/src/main/res/mipmap-xxhdpi/logo_foreground.png
  app/src/main/res/mipmap-xxhdpi/logo_launcher.png
  app/src/main/res/mipmap-xxxhdpi/logo_foreground.png
  app/src/main/res/mipmap-xxxhdpi/logo_launcher.png
Labels: duplicate, enhancement

#14 fix bug in the requested_job_view page
  .idea/misc.xml
  app/src/main/java/com/example/mysaved/RequestJob.java
  app/src/main/res/layout/activity_view_req_job.xml
Labels: duplicate, enhancement

#15 fix bug in the requested_job_view page
  app/src/main/res/layout/activity_requestjob.xml
  app/src/main/res/layout/activity_view_req_job.xml
Labels: bug

#20 Feature/careers
  app/src/main/res/layout/activity_edit_jobreq.xml
  app/src/main/res/layout/activity_viewjob_m.xml
Labels: duplicate, enhancement

#21 Change profile ui and its java class intent page, Change menue icon c…
  .idea/misc.xml
  app/src/main/res/drawable/ic_baseline_menu.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_requestjob.xml
  app/src/main/res/layout/activity_view_req_job.xml
  app/src/main/res/layout/toolbar1.xml
Labels: duplicate

#23 Feature/appearance
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/res/drawable/intlogo.png
  app/src/main/res/layout/activity_create_job.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_requestjob.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/activity_view_req_job.xml
Labels: duplicate

#24 updated nav icons
  .idea/misc.xml
  app/src/main/res/drawable/savedi.jpg
  app/src/main/res/layout/activity_navigation_bar.xml
Labels: duplicate, enhancement

#25 Feature/careers
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout/activity_my_job_listings.xml
  app/src/main/res/layout/activity_my_requested_jobs.xml
  app/src/main/res/layout/activity_view_req_job.xml
  app/src/main/res/layout/activity_viewjob_m.xml
  app/src/main/res/layout/register_user.xml
Labels: enhancement

#26 edit tharindu's UI pages
  app/src/main/res/layout/activity_edit_job.xml
  app/src/main/res/layout/activity_my_salary_calc.xml
  app/src/main/res/layout/activity_navigation_bar.xml
  app/src/main/res/layout/activity_new_saved_jobs.xml
  app/src/main/res/layout/activity_userlogin.xml
  app/src/main/res/layout/register_user.xml
Labels: enhancement

#27 Feature/appearance
  app/src/main/res/drawable/tt.gif
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_requestjob.xml
Labels: enhancement

#28 edit
  app/src/main/res/layout/activity_navigation_bar.xml
Labels: enhancement

#29 set component with alignment
  .idea/misc.xml
  app/src/main/res/layout/activity_editprofile.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_view_req_job.xml
Labels: duplicate

#30 changed UIs
  app/src/main/res/layout/activity_navigation_bar.xml
  app/src/main/res/layout/activity_userlogin.xml
  app/src/main/res/layout/activity_view_req_job.xml
  app/src/main/res/layout/activity_viewjob_m.xml
Labels: enhancement

#31 Feature/careers
  app/src/main/res/drawable/search.gif
  app/src/main/res/layout/activity_homepage_new.xml
  app/src/main/res/layout/activity_view_req_job.xml
Labels: enhancement

#32 edited Uis
  app/src/main/res/layout/activity_edit_jobreq.xml
Labels: enhancement

#33 Feature/appearance
  .idea/misc.xml
  app/src/main/res/drawable/lt.png
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/activity_userlogin.xml
  app/src/main/res/layout/activity_view_req_job.xml
Labels: duplicate, enhancement

#34 fix some UI components
  app/src/main/res/layout/activity_editprofile.xml
  app/src/main/res/layout/activity_new_saved_jobs.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_view_req_job.xml
  app/src/main/res/layout/savejobs_item.xml
Labels: enhancement

#35 fix java files
  app/src/main/java/com/example/mysaved/EditJob.java
  app/src/main/java/com/example/mysaved/EditJobReq.java
  app/src/main/java/com/example/mysaved/MyJobListings.java
  app/src/main/java/com/example/mysaved/New_SaveReq_Jobs.java
  app/src/main/java/com/example/mysaved/New_Saved_Jobs.java
  app/src/main/java/com/example/mysaved/RegisterUserActivity.java
  app/src/main/java/com/example/mysaved/UserloginActivity.java
  app/src/main/java/com/example/mysaved/ViewJob.java
  app/src/main/java/com/example/mysaved/ViewReqJob.java
  app/src/main/res/layout/listing_card.xml
Labels: enhancement

#36 change profile page ui and edit create job validation
  .idea/misc.xml
  app/src/main/java/com/example/mysaved/CreateJob.java
  app/src/main/res/layout/activity_create_job.xml
  app/src/main/res/layout/activity_editprofile.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_requestjob.xml
Labels: bug, documentation, enhancement

#38 fix salary calculation page bug
  app/src/main/java/com/example/mysaved/my_salary_calc.java
  app/src/main/res/layout/activity_my_salary_calc.xml
  app/src/main/res/layout/activity_profile.xml
Labels: bug, duplicate

#39 fix bugs
  .idea/misc.xml
  app/src/main/res/layout/activity_profile.xml
Labels: enhancement

#40 Feature/careers
  app/src/main/res/layout/activity_create_job.xml
  app/src/main/res/layout/activity_requestjob.xml
  app/src/main/res/layout/activity_view_job.xml
  app/src/main/res/layout/activity_viewjob_m.xml
Labels: enhancement

#45 salary calculator ,create some ui chnages
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mysaved/ViewjobM.java
  app/src/main/java/com/example/mysaved/my_salary_calc.java
  app/src/main/res/drawable/ic_baseline_salcal.xml
  app/src/main/res/layout/activity_my_salary_calc.xml
  app/src/main/res/layout/activity_viewjob_m.xml
  app/src/main/res/layout/register_user.xml
Labels: enhancement

#46 fix bugs
  app/src/main/res/layout/activity_editprofile.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement
